[2023-01-14T17:35:22.456+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag_v5.3rd_task manual__2023-01-14T17:33:09.902338+00:00 [queued]>
[2023-01-14T17:35:22.494+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag_v5.3rd_task manual__2023-01-14T17:33:09.902338+00:00 [queued]>
[2023-01-14T17:35:22.495+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T17:35:22.496+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-14T17:35:22.497+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T17:35:22.542+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-01-14 17:33:09.902338+00:00
[2023-01-14T17:35:22.550+0000] {standard_task_runner.py:54} INFO - Started process 21 to run task
[2023-01-14T17:35:22.558+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag_v5', '3rd_task', 'manual__2023-01-14T17:33:09.902338+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpvkgik4v2']
[2023-01-14T17:35:22.561+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask 3rd_task
[2023-01-14T17:35:22.564+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/repo/Airflow/dags/first_dag.py
[2023-01-14T17:35:27.873+0000] {task_command.py:384} INFO - Running <TaskInstance: first_dag_v5.3rd_task manual__2023-01-14T17:33:09.902338+00:00 [running]> on host firstdagv53rdtask-d1a2ed029a4447d0996c82e98622147f
[2023-01-14T17:35:31.937+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_dag_v5
AIRFLOW_CTX_TASK_ID=3rd_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T17:33:09.902338+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-14T17:33:09.902338+00:00
[2023-01-14T17:35:31.939+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-14T17:35:31.941+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'will run after task1, run with task2']
[2023-01-14T17:35:31.971+0000] {subprocess.py:86} INFO - Output:
[2023-01-14T17:35:31.982+0000] {subprocess.py:93} INFO - /bin/bash: line 1: will: command not found
[2023-01-14T17:35:31.983+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-01-14T17:35:32.017+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-14T17:35:32.027+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=first_dag_v5, task_id=3rd_task, execution_date=20230114T173309, start_date=20230114T173522, end_date=20230114T173532
[2023-01-14T17:35:32.067+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 127.; 21)
[2023-01-14T17:35:32.658+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-14T17:35:32.713+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
