[2023-01-15T01:16:05.683+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag_v5.3rd_task scheduled__2023-01-14T00:00:00+00:00 [queued]>
[2023-01-15T01:16:05.712+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag_v5.3rd_task scheduled__2023-01-14T00:00:00+00:00 [queued]>
[2023-01-15T01:16:05.713+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T01:16:05.713+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-15T01:16:05.714+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T01:16:05.767+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-01-14 00:00:00+00:00
[2023-01-15T01:16:05.775+0000] {standard_task_runner.py:54} INFO - Started process 22 to run task
[2023-01-15T01:16:05.785+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag_v5', '3rd_task', 'scheduled__2023-01-14T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp85qwk0by']
[2023-01-15T01:16:05.788+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask 3rd_task
[2023-01-15T01:16:05.792+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/repo/Airflow/dags/first_dag.py
[2023-01-15T01:16:06.110+0000] {task_command.py:384} INFO - Running <TaskInstance: first_dag_v5.3rd_task scheduled__2023-01-14T00:00:00+00:00 [running]> on host firstdagv53rdtask-5ab4169c3a6a43bd897aad5ffaf3765f
[2023-01-15T01:16:09.384+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_dag_v5
AIRFLOW_CTX_TASK_ID=3rd_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-14T00:00:00+00:00
[2023-01-15T01:16:09.387+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-15T01:16:09.389+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'will run after task1, run with task2']
[2023-01-15T01:16:09.414+0000] {subprocess.py:86} INFO - Output:
[2023-01-15T01:16:09.420+0000] {subprocess.py:93} INFO - /bin/bash: line 1: will: command not found
[2023-01-15T01:16:09.421+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-01-15T01:16:09.451+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-15T01:16:09.461+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=first_dag_v5, task_id=3rd_task, execution_date=20230114T000000, start_date=20230115T011605, end_date=20230115T011609
[2023-01-15T01:16:09.502+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 127.; 22)
[2023-01-15T01:16:09.573+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-15T01:16:09.621+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
