[2023-01-17T09:53:15.159+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag_v5.2nd_task scheduled__2023-01-16T00:00:00+00:00 [queued]>
[2023-01-17T09:53:15.192+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag_v5.2nd_task scheduled__2023-01-16T00:00:00+00:00 [queued]>
[2023-01-17T09:53:15.193+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T09:53:15.194+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-17T09:53:15.194+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T09:53:15.257+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): 2nd_task> on 2023-01-16 00:00:00+00:00
[2023-01-17T09:53:15.262+0000] {standard_task_runner.py:54} INFO - Started process 21 to run task
[2023-01-17T09:53:15.272+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag_v5', '2nd_task', 'scheduled__2023-01-16T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp_8lk38qz']
[2023-01-17T09:53:15.275+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask 2nd_task
[2023-01-17T09:53:15.278+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/repo/Airflow/dags/first_dag.py
[2023-01-17T09:53:15.543+0000] {task_command.py:384} INFO - Running <TaskInstance: first_dag_v5.2nd_task scheduled__2023-01-16T00:00:00+00:00 [running]> on host firstdagv52ndtask-e026590139d747b39d71b586242057d9
[2023-01-17T09:53:18.631+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_dag_v5
AIRFLOW_CTX_TASK_ID=2nd_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-16T00:00:00+00:00
[2023-01-17T09:53:18.633+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-17T09:53:18.634+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'will run after task1']
[2023-01-17T09:53:18.653+0000] {subprocess.py:86} INFO - Output:
[2023-01-17T09:53:18.658+0000] {subprocess.py:93} INFO - /bin/bash: line 1: will: command not found
[2023-01-17T09:53:18.659+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-01-17T09:53:18.692+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-17T09:53:18.701+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=first_dag_v5, task_id=2nd_task, execution_date=20230116T000000, start_date=20230117T095315, end_date=20230117T095318
[2023-01-17T09:53:18.741+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task 2nd_task (Bash command failed. The command returned a non-zero exit code 127.; 21)
[2023-01-17T09:53:18.821+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-17T09:53:18.893+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
