[2023-01-14T17:35:28.509+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag_v5.2nd_task manual__2023-01-14T17:33:09.902338+00:00 [queued]>
[2023-01-14T17:35:28.539+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag_v5.2nd_task manual__2023-01-14T17:33:09.902338+00:00 [queued]>
[2023-01-14T17:35:28.540+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T17:35:28.541+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-14T17:35:28.542+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T17:35:28.585+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): 2nd_task> on 2023-01-14 17:33:09.902338+00:00
[2023-01-14T17:35:28.594+0000] {standard_task_runner.py:54} INFO - Started process 21 to run task
[2023-01-14T17:35:28.603+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag_v5', '2nd_task', 'manual__2023-01-14T17:33:09.902338+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpug9ivlgo']
[2023-01-14T17:35:28.607+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask 2nd_task
[2023-01-14T17:35:28.610+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/repo/Airflow/dags/first_dag.py
[2023-01-14T17:35:28.902+0000] {task_command.py:384} INFO - Running <TaskInstance: first_dag_v5.2nd_task manual__2023-01-14T17:33:09.902338+00:00 [running]> on host firstdagv52ndtask-4132a1d1160b4ca0a4c061b9275deac9
[2023-01-14T17:35:32.508+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_dag_v5
AIRFLOW_CTX_TASK_ID=2nd_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T17:33:09.902338+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-14T17:33:09.902338+00:00
[2023-01-14T17:35:32.511+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-14T17:35:32.512+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'will run after task1']
[2023-01-14T17:35:32.536+0000] {subprocess.py:86} INFO - Output:
[2023-01-14T17:35:32.540+0000] {subprocess.py:93} INFO - /bin/bash: line 1: will: command not found
[2023-01-14T17:35:32.542+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-01-14T17:35:32.576+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-14T17:35:32.587+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=first_dag_v5, task_id=2nd_task, execution_date=20230114T173309, start_date=20230114T173528, end_date=20230114T173532
[2023-01-14T17:35:32.626+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task 2nd_task (Bash command failed. The command returned a non-zero exit code 127.; 21)
[2023-01-14T17:35:32.697+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-14T17:35:32.749+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
